language: python
python: "2.7"
sudo: false

env:
  global:
    - DJANGO_VERSION=1.9b1
    - DB=mysql
    - DJANGO_SETTINGS=collectf.settings.travis_ci

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flake8  

before_script:
  - flake8 .
  - mysql -e 'create database collectfdb_devel;'

script:
  coverage run --source='src/' src/manage.py test --settings=$DJANGO_SETTINGS

after_success:
  coveralls