language: python
python: "2.7"

env:
  - DJANGO_VERSION=1.6.1 DB=mysql BUILD_ON_TRAVIS=true

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - mysql -e 'create database test_collectfdb;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - python manage.py syncdb --noinput

script:
  coverage run manage.py test

after_success:
  coveralls

  