language: python
python: "2.7"

env:
  - DJANGO_VERSION=1.9b1 DB=mysql BUILD_ON_TRAVIS=true

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flake8  

before_script:
  - flake8 .
  - mysql -e 'create database collectfdb_test;'
  - python manage.py syncdb --noinput

script:
  coverage run manage.py test

after_success:
  coveralls