language: python
python: "2.7"

env:
  - DJANGO_VERSION=1.9b1 DB=mysql

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flake8  

before_script:
  - flake8 .
  - mysql -e 'create database collectfdb_devel;'
  - python src/manage.py migrate

script:
  coverage run --source='src/' src/manage.py test --settings=collectf.settings.travis_ci

after_success:
  coveralls